Container:
  Name: cve-consumer
  # Image: vamsidharp/webapp-cve-consumer:v4
  # Image: vamsidharp/producerpartition:v5
  Image: vamsidharp/consumerpart:v1

metadata:
  name: cve-consumer-pod
  labels:
    app: cve-consumer

InitContainer:
  Image: vamsidharp/flyway:v3
  Name: init-cve-consumer
