Container:
  Name: cve-consumer
  Image: vamsidharp/webapp-cve-consumer:v1

metadata:
  name: cve-consumer-pod
  labels:
    app: cve-consumer
  job-name: cve-pod

InitContainer:
  Image: vamsidharp/flywaydb:v2
  Name: init-cve-consumer
