apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cve-consumer-role
  namespace: webapp-cve-consumer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]