apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
    spec:
      initContainers:
        - name: {{ .Values.InitContainer.Name }}
          image: {{ .Values.InitContainer.Image }}
          command: ["flyway", "migrate"]
          envFrom:
            - secretRef:
                name: cve-consumer-secrets
      containers:
        - name: {{ .Values.Container.Name }}
          image: {{ .Values.Container.Image }}
          envFrom:
            - secretRef:
                name: cve-consumer-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      imagePullSecrets:
        - name: docker-creds
      restartPolicy: Always
  backoffLimit: 4
